"""
Created on Sat Jul 18 16:43:31 2020

author: Mark Dransfield

A library of geophysical QA QC functions for gridded data.

"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
from pathlib import Path
import colorcet as cc
import xarray as xr
import netCDF4 as nc4
import filebrowser as fb
import rioxarray
import h5py
import pygmt
import matplotlib.ticker as tkr
# from matplotlib import rc
plt.rc('font',**{'family':'sans-serif','sans-serif':['Helvetica Neue']})

SMALL_SIZE = 6
MEDIUM_SIZE = 8
BIGGER_SIZE = 10

plt.rc('font', size=SMALL_SIZE)          # controls default text sizes
plt.rc('axes', titlesize=SMALL_SIZE)     # fontsize of the axes title
plt.rc('axes', labelsize=MEDIUM_SIZE)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('ytick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('legend', fontsize=SMALL_SIZE)    # legend fontsize
plt.rc('figure', titlesize=BIGGER_SIZE)  # fontsize of the figure title

import AirGravQC.graphics as graphics
import AirGravQC.utility.utility as util
import AirGravQC.gridFiles.read_ers as ers
import AirGravQC.whizzFiles.pointfiles as gw
import AirGravQC.config as config

groupName = config.groupName
projectName = config.projectName


# GRID FILE MANAGEMENT


# GRID PLOTTING

def image_pygmt(grid, region):
    """
    Shows a figure of an image of `grid` over a `region`, using
    `PyGMT`'s `grdimage()`. The inputs are generated by `xarray_to_grid()`.

    Parameters
    ----------
    grid : XArray
        Contains the gridded data.
    region : tuple
        Four floating point values for xmin, xmax, ymin, ymax.

    Returns
    -------
    Nothing.

    """

    plot_width = 0.12 # ie 12 cm

    # colour bar labeling
    yc_label = f'af+l{grid.attrs["long_name"]}'
    uc_label = f'y+l{grid.attrs["units"]}'

    # axis labeling and control
    xa_label = f"xag+l{grid['x'].attrs['orig_name']}"
    ya_label = f"yag+l{grid['y'].attrs['orig_name']}"
    my_title = f'+t{grid.attrs["title"]}'

    # Colour scaling
    cmin = np.nanpercentile(grid.data, 1)
    cmax = np.nanpercentile(grid.data, 99)
    print(f'z range (1st to 99th percentile) ({cmin:.4g}, {cmax:.4g})')
    if abs(cmax - cmin) < 1.0E-10:
        cmin = -1.0E-10
        cmax = 1.0E-10

    # fit the plot to a width of 12 cm
    hscale = (grid['x'].attrs['actual_range'][1] - grid['x'].attrs['actual_range'][0]) / plot_width
    myproj = f'x1:{hscale:.0f}'

    fig = pygmt.Figure()
    fig.basemap(
        frame=[xa_label, ya_label, my_title],
        region=region,
        projection=myproj,
    )
    pygmt.makecpt(cmap="viridis", series=(cmin, cmax))
    fig.grdimage(grid=grid, nan_transparent=True, cmap=True)
    fig.colorbar(position="JMR", frame=[yc_label, uc_label])
    fig.show()



# GRID REPORTING



def whizz_to_xarray(whizz_file, z_chan, n_chan='', e_chan='', lines=[], remove_mean=False, diff_one=False):
    """
    Return a point-located xArray Dataset of (northing, easting, z), over the `fiducials` dimension,
    from a whizz_file.

    Parameters
    ----------
    whizzFile : Path or String
        The Path to, or String name of, the whizz file in HDF5 format.
    z_chan : String
        The name of the channel in `whizz_file` to be imaged.
    n_chan : String, optional
        The name of the channel in `whizz_file` containing the northings (y).
        Default "" causes the name of the "YChannel" in `whizz_file` to be used.
    e_chan : String, optional
        The name of the channel in `whizz_file` containing the eastings (x).
        Default "" causes the name of the "XChannel" in `whizz_file` to be used.
    remove_mean : Bool, optional
        If true, the mean is subtracted from each survey line of data before
        writing to `my_dataset`. Default False.
    diff_one : Bool, optional
        If true, the first difference along each survey line of data is
        written to `my_dataset`. Default False.

    Returns
    -------
    my_dataset : xArray Dataset
        Contains the data. If `whizz_to_xarray()` is unable to return data,
        it returns an empty xArray Dataset (test with `len(aa.attrs) == 0`).

    """
    filename = str(whizz_file)
    
    with h5py.File(filename, 'r') as f:
        lines_group = f[groupName]['Lines']
        projName = f[groupName].attrs['ProjectName']
        if e_chan == '':
            e_chan = f[groupName]['CoordinateFrame'].attrs['XChannel']
        if n_chan == '':
            n_chan = f[groupName]['CoordinateFrame'].attrs['YChannel']

        if not remove_mean and not diff_one and (z_chan == e_chan or z_chan == n_chan):
            print(f'Cannot process {z_chan}, same as {e_chan} or {n_chan}.')
            return xr.Dataset()
        totalNumFids = 0

        if lines == []:
            lines = lines_group.keys()
        
        for line in lines:
            xData = gw.getLineData(lines_group[line], e_chan)
            totalNumFids += len(xData)
        print(f'{len(lines)} lines; total number of fids in whizz file = {totalNumFids}.')

        # initialise an xarray to take the data, with name and units
        fiducials = np.arange(0, totalNumFids)
        data = np.zeros((totalNumFids,))
        eastings = np.zeros((totalNumFids,))
        northings = np.zeros((totalNumFids,))

        if remove_mean and diff_one:
            xr_zchan = f'D1_MR_{z_chan}'
        elif remove_mean:
            xr_zchan = f'MR_{z_chan}'
        elif diff_one:
            xr_zchan = f'D1_{z_chan}'
        else:
            xr_zchan = f'{z_chan}'

        my_dataset = xr.Dataset({
            e_chan: xr.DataArray(
                data = eastings,
                coords={'fiducials': fiducials}, 
                dims = ['fiducials'],
                attrs = {
                    'units': 'm'
                }
            ),
            n_chan: xr.DataArray(
                data = northings,
                coords={'fiducials': fiducials}, 
                dims = ['fiducials'],
                attrs = {
                    'units': 'm'
                }
            ),
            xr_zchan: xr.DataArray(
                data = np.zeros((totalNumFids,)),
                coords={'fiducials': fiducials}, 
                dims = ['fiducials'],
                attrs = {
                    'units': '-'
                }
            )},
            attrs = {
            'author': 'Mark Dransfield',
            'x_channel': e_chan,
            'y_channel': n_chan,
            'z_channel': xr_zchan
            }
        )

        sfid = 0
        efid = 0
        for line in lines:
            sfid = efid
            xData = gw.getLineData(lines_group[line], e_chan)
            yData = gw.getLineData(lines_group[line], n_chan)
            zData = gw.getLineData(lines_group[line], z_chan)
            efid += len(yData)
            if remove_mean:
                zData = zData - np.mean(zData)
            if diff_one:
                zData = np.append(np.diff(zData), zData[-1]-zData[-2])

            my_dataset[e_chan][sfid:efid] = xData
            my_dataset[n_chan][sfid:efid] = yData
            my_dataset[xr_zchan][sfid:efid] = zData

            my_dataset[e_chan].attrs['units'] = gw.getChannelAttrs(lines_group[line], e_chan)
            my_dataset[n_chan].attrs['units'] = gw.getChannelAttrs(lines_group[line], n_chan)
            my_dataset[xr_zchan].attrs['units'] = gw.getChannelAttrs(lines_group[line], z_chan)
            if remove_mean and diff_one:
                my_dataset.attrs['title'] = f'{z_chan} (mr) (d1)'
            elif remove_mean:
                my_dataset.attrs['title'] = f'{z_chan} (mr)'
            elif diff_one:
                my_dataset.attrs['title'] = f'{z_chan} (d1)'
            else:
                my_dataset.attrs['title'] = z_chan
            
        print(f'    {my_dataset.attrs["title"]}: min = {my_dataset[xr_zchan].data.min()}, max = {my_dataset[xr_zchan].data.max()}.')
    return my_dataset


def xarray_to_grid(my_data, grid_space, region=[]):
    """
    Uses `PyGMT` to interpolate `my_data` onto a regular grid. Method
    uses data to 5 x the grid spacing to focus on QC issues.

    Parameters
    ----------
    my_data : xArray Dataset
        Contains x, y, and z data dimensioned by fiducial.

    Returns
    -------
    grid : XArray
        Contains the gridded data.
    region : tuple
        Four floating point values for xmin, xmax, ymin, ymax.
    grid_space : Float
        The distance between grid cell centres in grid distance units.

    """

    # grid_space = 500.0

    x_chan = my_data.attrs['x_channel']
    y_chan = my_data.attrs['y_channel']
    z_chan = my_data.attrs['z_channel']
    if 'units' in my_data[z_chan].attrs:
        myunits = my_data[z_chan].attrs['units']
    else:
        myunits = " "
    print(f'Processing (x, y, z) = ({x_chan}, {y_chan}, {z_chan}). {z_chan} in {myunits}.')

    # grid spacing and search radius
    inspc = f'{grid_space:.0f}+e'
    maxradius = 5.0 * grid_space

    if region == []:
        region = pygmt.info(data=my_data[[x_chan, y_chan]], spacing=1)  # West, East, South, North
    print(f"Data points cover region: {region}")

    # Preprocess z_chan data using blockmedian
    data_trm = pygmt.blockmedian(
        data=my_data[[x_chan, y_chan, z_chan]],
        spacing=inspc,
        region=region,
    )

    # make grid
    grid = pygmt.surface(
        x=data_trm[0],
        y=data_trm[1],
        z=data_trm[2],
        spacing=inspc,
        M=maxradius,
        region=region,  # xmin, xmax, ymin, ymax
        T=0.35,  # tension factor
    )

    grid.attrs['units'] = myunits
    grid.attrs['long_name'] = z_chan
    grid.attrs['title'] = my_data.attrs['title']
    grid['x'].attrs['orig_name'] = x_chan
    grid['y'].attrs['orig_name'] = y_chan

    return grid, region


def oddevenlines(whizz_file, channel, grid_space):
    """
    """
    filename = str(whizz_file)
    evens = []
    odds = []
    
    with h5py.File(filename, 'r') as f:
        lines_group = f[groupName]['Lines']
        lines = lines_group.keys()
        
        for line in lines:
            planned = lines_group[line].attrs['PlannedLine']
            if planned % 2 == 0:
                evens.append(line)
            else:
                odds.append(line)

    even_data = whizz_to_xarray(whizz_file, channel, n_chan='', e_chan='', lines=evens, remove_mean=False, diff_one=False)
    odd_data = whizz_to_xarray(whizz_file, channel, n_chan='', e_chan='', lines=odds, remove_mean=False, diff_one=False)

    even_grid, even_region = xarray_to_grid(even_data, grid_space)
    odd_grid, odd_region = xarray_to_grid(odd_data, grid_space)

    intersectregion = [
                        max(even_region[0], odd_region[0]),
                        min(even_region[1], odd_region[1]),
                        max(even_region[2], odd_region[2]),
                        min(even_region[3], odd_region[3]),
                        ]
    even_grid, even_region = xarray_to_grid(even_data, grid_space, region=intersectregion)
    odd_grid, odd_region = xarray_to_grid(odd_data, grid_space, region=intersectregion)
    d_grid = even_grid - odd_grid

    # Subtraction does not preserve attributes
    d_grid.attrs['units'] = even_grid.attrs['units']
    d_grid.attrs['long_name'] = even_grid.attrs['long_name']
    d_grid.attrs['title'] = f"even minus odd : {even_grid.attrs['title']}"
    d_grid['x'].attrs['orig_name'] = even_grid['x'].attrs['orig_name']
    d_grid['y'].attrs['orig_name'] = even_grid['y'].attrs['orig_name']

    image_pygmt(d_grid, intersectregion)
    print(f'RMS of odd-even difference = {d_grid.std().data.item():.2f}')


def grid_n_image(whizz_file, z_chans, mr_chans, d1_chans, grid_space, lines=[], n_chan='', e_chan='', sh_chans=[]):
    """
    Every channel in `z_chans` from `whizz_file` is interpolated onto a grid and imaged.
    Channels listed in `mr_chans` have the mean value of each survey line subtracted first.
    Channels listed in `d1_chans` are first differenced along each survey line first.

    Parameters
    ----------
    whizzFile : Path or String
        The Path to, or String name of, the whizz file in HDF5 format.
    z_chans : [String]
        An array of names of channels in `whizz_file` to be interpolated to a regular grid and imaged.
    mr_chans : [String]
        An array of names of channels from `z_chans` whose mean along each survey line should be subtracted before gridding and imaging.
    d1_chans : [String]
        An array of names of channels from `z_chans` whose first difference along each survey line should be gridded and imaged.
    sh_chans : [String]
        An array of names of channels from `z_chans` whose imaged grid will be shaded.
    grid_space : Float
        The distance between grid cell centres in grid distance units.

    Returns
    -------
    Nothing.

    """
    for z_chan in z_chans:
        remove_mean = False
        diff_one = False
        shaded = False
        if z_chan in mr_chans:
            remove_mean = True
        if z_chan in d1_chans:
            diff_one = True
        if z_chan in sh_chans:
            shaded = True

        print(f'Gridding and imaging {z_chan}')
        my_data = whizz_to_xarray(whizz_file, z_chan, n_chan=n_chan, e_chan=e_chan, lines=lines, remove_mean=remove_mean, diff_one=diff_one)
        if len(my_data.attrs) == 0:
            continue
        my_grid, my_region = xarray_to_grid(my_data, grid_space)
        if shaded == False:
            xdImage(my_grid, f'{z_chan}', hs=False)
        else:
            xdImage(my_grid, f'{z_chan}')


def diff_n_image(whizz_file, channel1, channel2, grid_space):
    """
    Subtracts the data in `channel2` from those in `channel1`, then grids and images that difference.

    Parameters
    ----------
    whizzFile : Path or String
        The Path to, or String name of, the whizz file in HDF5 format.
    channel1 : String
        A name of a channel in `whizz_file`.
    channel2 : String
        A name of a channel in `whizz_file`.
    grid_space : Float
        The distance between grid cell centres in grid distance units.

    Returns
    -------
    Nothing.

    """
    print(f'Gridding and imaging {channel1} - {channel2}.')
    my_data1 = whizz_to_xarray(whizz_file, channel1, remove_mean=False, diff_one=False)
    my_data2 = whizz_to_xarray(whizz_file, channel2, remove_mean=False, diff_one=False)
    my_data1[channel1] = my_data1[channel1] - my_data2[channel2]
    my_data1.attrs['title'] = f'{channel1} - {channel2}'
    my_grid, my_region = xarray_to_grid(my_data1, grid_space)
    image_pygmt(my_grid, my_region)


def imageStats(whizzFile=''):
    """
    Returns the basic statistics of the data in a grid file. The range,
    number of points, and spacings of northing and easting and the range, number
    of samples, mean, standard deviation, and number of real and missing values
    are reported.

    Parameters
    ----------
    whizzFile : Path, optional
        The Path to the grid file in either ERS or NC format. Default is '' in
        which case a file browser allows the user to select the grid file.

    Returns
    -------
    report (String) : the statistical summary report.

    """
    xs, fileUsed = gridfile_to_xr(whizzFile, bandout=0)
    
    # Need to extract a DataArray from xs
    xa = xs
    
    report = f'Statistics for {str(fileUsed.name)}'
    report += f'\n Datum  {xa.attrs["datum"]}; Projection {xa.attrs["projection"]}'
    for coord in xa.coords:
        report += f'\n {coord} from {np.nanmin(xa[coord])} to {np.nanmax(xa[coord])}; {xa[coord].shape[0]} samples at spacing {xa[coord].values[1] - xa[coord].values[0]}'
    report += f'\n Value from {np.nanmin(xa.values):.2f} to {np.nanmax(xa.values):.2f}; {xa.values.shape[0]} x {xa.values.shape[1]} samples'
    report += f'\n     Mean = {np.nanmean(xa.values):.2f}, Stdev = {np.nanstd(xa.values):.2f}'
    report += f'\n     Number of real values = {np.count_nonzero(~np.isnan(xa.values))}, Number of nans = {np.count_nonzero(np.isnan(xa.values))}'
    return report


def checkTCratio(file000, filexxx, xxx, fileyyy, yyy, plotTitle):
    """
    Shows an image of the difference between data terrain-corrected
    at density y and the prediction based on un-corrected data and
    data terrain-corrected at x.

    Used to QC for consistency in terrain corrections.

    Parameters
    ----------
    file000 : String
        Name of the file containing the data before terrain correction.
    filexxx : String
        Name of the file containing the data after xpxx terrain correction.
    xxx : Float
        The density used in the filexxx terrain correction.
    fileyyy : String
        Name of the file containing the data after ypyy terrain correction.
    yyy : Float
        The density used in the fileyyy terrain correction.
    plotTitle : String
        A title for the plot of the difference between predicted and actual
        data in fileyyy.

    Returns
    -------
    None.

    """
    n, e, g0 = ers.read_ers_image(file000)
    n, e, gx = ers.read_ers_image(filexxx)
    n, e, gy = ers.read_ers_image(fileyyy)
    
    tx = g0 - gx
    predy = g0 - yyy / xxx * tx
    predErr = predy - gy
    graphics.graphicsShaded(n, e, predErr, plotTitle,  hs=False, colormap=cc.m_CET_L9, cmap_norm='no', azdeg=90)


def traceImages(file1, file2, file3, plotTitle):
    """
    Plots an image of the trace of the three diagonal components of the tensor.

    Parameters
    ----------
    file1 : String
        A grid file containing the first diagonal tensor component.
    file2 : String
        A grid file containing the second diagonal tensor component.
    file3 : String
        A grid file containing the third diagonal tensor component.
    plotTitle : String
        A title for the plot of the trace image.

    Returns
    -------
    None.

    """
    n1, e1, z1 = ers.read_ers_image(file1)
    n2, e2, z2 = ers.read_ers_image(file2)
    n3, e3, z3 = ers.read_ers_image(file3)
    trace = z1 + z2 + z3
    graphics.graphicsShaded(n1, e1, trace, plotTitle,  hs=False, colormap=cc.m_CET_L9, cmap_norm='no', azdeg=90)


def subtractImages(imagefile1, imagefile2, scale=1.0, band1=0, band2=0):
    """
    Takes in the paths to two grid files Each may be a single band ERMapper image
    file or a netCDF4 grid file) and returns the difference as an xarray:

    `imagefile1 - scale x imagefile2`.

    If the images do not cover the same space, then the return flag is set False
    and only the first image is returned.

    Parameters
    ----------
    imagefile1 : Path
        The Path to the first grid file, must have extension `ers` or `nc`.
    imagefile2 : Path
        The Path to the second grid file, must have extension `ers` or `nc`.
    scale : (Float, optional)
        imagefile2 is multiplied by scale before subtraction. Default 1.0.

    Returns
    -------
    flag : Bool
        True if operation was successful.
    x : xarray
        The difference if both span the same coordinates, otherwise the first.

    """
    
    x1, _ = gridfile_to_xr(imagefile1, bandout=band1)
    x2, _ = gridfile_to_xr(imagefile2, bandout=band2)
    
    try:
        xr.testing.assert_equal(x1.coords, x2.coords) #x1.coords.all() == x2.coords.all():
        return True, x1 - scale * x2
    except:
        return False, x1


def gridfile_to_xr(whizzFile='', bandout=0):
    """
    Returns an xarray Dataset containing the geographically located data from a
    gridfile in either ERS or NC format.

    Parameters
    ----------
    whizzFile : Path
        The Path to the grid file, must have extension `ers` or `nc`.
    bandout : Int, optional
        The band to be read if the grid file is `ERS`. The default is 0.

    Returns
    -------
    xd : xarray Dataset
        The data from `whizzFile`.

    """
    if whizzFile == '':
        whizzFile = Path(fb.get_grid_filename(filetypes=(('NetCdf4 grid', '*.nc'),
                                                         ('ERMapper grid', '*.ers'))))
    if whizzFile.suffix.upper() == '.ERS':
        e, n, z, datum, projection = ers.read_ers_image(whizzFile, bandout=bandout)
        xa = xr.DataArray(data=z,#np.flip(z, 0), # DANGER!!!
                          dims=["N", "E"],
                          coords={"N": n, "E": e})
        xa.dropna(dim='N',how='all')
        xa.dropna(dim='E',how='all')
        fname = whizzFile.with_suffix('').name
        xd = xr.Dataset(data_vars={fname: xa})
        xd.attrs["long_name"] = fname
        xd.attrs["datum"] = datum
        xd.attrs["projection"] = projection
        if datum == 'WGS84' and projection == 'SUTM55':
            xd.rio.write_crs("epsg:32755", inplace=True)
    elif whizzFile.suffix.upper() == '.NC':
        nc = nc4.Dataset(str(whizzFile), mode='r')
        xd = xr.open_dataset(xr.backends.NetCDF4DataStore(nc))
    else:
        print(f'ERROR: whizzFile has suffix {Path(whizzFile).suffix.upper()} but must be `.nc` or `.ers`.')
    return xd, whizzFile


def ers_to_netcdf4(ersFile='', ncFile='', datum='', projection='', long_name='', units=''):
    """
    Writes an `ERS` grid to a netCDF4 file.

    Parameters
    ----------
    ersFile : pathlib Path, optional
        The ERS grid file to be converted. The default is ''. If '', then file browser allows
        the user to select the file.
    ncFile : pathlib Path, optional
        The NC file to be written. The default is ''. if '', then the name of the ERS file is
        used, with the 'NC' extension.
    datum : Str, optional
        The geographic datum. The default is ''. If '', it is read from the ERS file.
    projection : Str, optional
        The geographic projection. The default is ''. If '', it is read from the ERS file.
    long_name : Str, optional
        The NC Dataset long_name attr. The default is ''. If '', then the ERS filename is used.
    units : Str, optional
        The units of the Dataarray values. The default is ''.

    Returns
    -------
    None.

    """
    if ersFile == '':
        ersFile = Path(fb.get_grid_filename(filetypes=[('ERMapper grid', '*.ers')]))
    if ncFile == '':
        ncFile = ersFile.with_suffix('.nc')
    xd, fname = gridfile_to_xr(ersFile)
    if datum == '':
        datum = xd.attrs['datum']
    if long_name == '':
        long_name = xd.attrs['long_name']
    if projection == '':
        projection = xd.attrs['projection']
    xd.attrs = {'datum' : datum,
                'projection' : projection,
                'long_name' : long_name,
                'units' : units}
    print(xd)
    xd.to_netcdf(ncFile)
     
    
def update_grid(whizzFile='', datum='', projection='', long_name='', units=''):
    """
    NOT FUNCTIONAL. Adds any specified (ignores the defaults) attributes to a NetCdf4 grid files DataSet.

    Parameters
    ----------
    whizzFile : String or Path, optional
        The name of the netCDF4 grid file, including the `.nc` extension. Defaults to
        putting up a filebrowser dialog so the user can select a file.
    datum : String, optional
        The geographic datum. The default is ''.
    projection : String, optional
        The geographic projection. The default is ''.
    long_name : String, optional
        A descriptive name for the grid. The default is ''.
    units : String, optional
        The units of the grid `z` field. The default is ''.

    Returns
    -------
    None.

    """
    if whizzFile == '':
        whizzFile = Path(fb.get_grid_filename([('NetCdf4 grid', '*.nc')]))
    nc = nc4.Dataset(str(whizzFile), mode='r')
    xa = xr.open_dataset(xr.backends.NetCDF4DataStore(nc))
    nc.close()
    xs = xa
    # xs.attrs = {'datum' : datum,
    #             'projection' : projection,
    #             'long_name' : long_name,
    #             'units' : units}
    suffix = whizzFile.suffix
    fname = whizzFile.with_suffix('').name + '+'
    newWhizz = whizzFile.with_name(fname).with_suffix(suffix)
    print(xs)
    xs.to_netcdf(newWhizz)

    
def display_grid(whizzFile, mytitle, colormap=cc.m_CET_L9, cmap_norm='nonorm', 
                   minClip=np.nan, maxClip=np.nan, cb_ticks='stats', nSigma=2,
                   hs=True, azdeg=45, ax=None, clipTo3Std = True):
    """
    Uses `xrImage()` to display the gridded data array in whizzFile. All
    parameters after the name of the whizzFile are just passed through
    to `xrImage()`.

    Parameters
    ----------
    whizzFile : TYPE, optional
        May be either an `ERS` or `NC` grid file. The default is ''.

    Returns
    -------
    None.

    """
    (xa, _) = gridfile_to_xr(whizzFile, bandout=0)
    xrImage(xa, mytitle, colormap=colormap, cmap_norm=cmap_norm, 
                       minClip=minClip, maxClip=maxClip, cb_ticks=cb_ticks, nSigma=nSigma,
                       hs=hs, azdeg=azdeg, ax=ax, clipTo3Std = clipTo3Std)
    
    
def displayImage(e, n, z, mytitle):
    """
    Given a 2D array z located by 1D arrays e and n, plot an image of z

    Any invalid values (NaN, Inf) of z are masked out. The plot has grid lines,
    colorbar, x and y labels (Eastings and Northings respectively) and a title.

    Parameters
    ----------
    e : numpy array
        The 1D array of eastings.
    n : numpy array
        The 1D array of northings.
    z : numpy array
        The 2D array of z values.
    mytitle : String
        The image plot title.

    Returns
    -------
    None.

    """
    zm = np.ma.masked_invalid(z)
    # might change to image histogram-equalised zm or limit the range to 95%
    # z indices ought to be fixed in ermread
    plt.figure(dpi=100)
    plt.pcolormesh(e, n, zm[::-1, :], cmap='gray')
    plt.axis('equal')
    plt.xlabel('Eastings [m]')
    plt.ylabel('Northings [m]')
    plt.title(mytitle)
    plt.grid(True)
    plt.colorbar()
    plt.show()

    return


def cmap_exists(name):
    """
    Returns True if the Matplotlib Colormap `name` exists.

    Parameters
    ----------
    name : Colormap instance
        The name of the Colormap.

    Returns
    -------
    bool

    """
    try:
         cm.get_cmap(name)
         return True
    except ValueError:
         pass
    return False


def imageAllInDir(path_name):
    """
    Quick and dirty method to image all the grids in a 
    directory for QC.

    Parameters
    ----------
    path_name : Path
        The Path where the ERS grid files are located.

    Returns
    -------
    None.

    """
    # get a list of the ers file paths
    file_count = 0
    ersFiles = []
    folderFiles = path_name.iterdir()
    for aFile in folderFiles:
        if aFile.is_file() and (aFile.suffix == '.ERS' or aFile.suffix == '.ers') and (aFile.name[0] != '.'):
            ersFiles.append(aFile)
            file_count += 1
    print(f'Found {file_count} .ers files ...')
    print(f'in: {str(path_name)}')

    for f in ersFiles:
        (dxt, _) = gridfile_to_xr(f)
        xrImage(dxt, str(f.name), colormap=cc.m_CET_R1)


def xrImage(data_array, mytitle, colormap=cc.m_CET_L9, cmap_norm='nonorm', 
        minClip=np.nan, maxClip=np.nan, cb_ticks='stats', nSigma=2,
        hs=True, azdeg=45, ax=None, clipTo3Std = True):
    """
    Uses `graphicsShaded()` to display the gridded data in data_array. All
    parameters after the name of the whizzFile are just passed through
    to `graphicsShaded()`.

    Assumes only one DataArray in the xarray dataset

    Parameters
    ----------
    data_array : 2D xarray dataset
        The data to be imaged.
    mytitle : String
        The figure title.
    colormap : Colormap, optional
        A colour map, eg cc.m_CET_L9. The default is cc.m_CET_L9.
    cmap_norm : String, optional
        Must be one of 'nonorm' (no normalisation, ie linear stretch); 'equalize'
        (equlaization stretch); 'auto'. The default is 'nonorm'.
    minClip : Float, optional
        z -> z < minClip : minClip: z. The default is np.nan - no clipping.
    maxClip : Float, optional
        z -> z > maxClip : maxClip: z. The default is np.nan - no clipping.
    cb_ticks : TYPE, optional
        DESCRIPTION. The default is 'stats'.
    nSigma : TYPE, optional
        Not currently used. The default is 2.
    hs : Bool, optional
        hill-shading. The default is True.

    Returns
    -------
    None.

    """
    vmin = np.nan
    vmax = np.nan
    first_data = list(data_array.keys())[0]
    fd_mean = data_array[first_data].mean()
    fd_std = data_array[first_data].std()
    if clipTo3Std:
        a = fd_mean - 3.0 * fd_std
        vmin = a.data * 1
        a = fd_mean + 3.0 * fd_std
        vmax = 1 * a.data
    elif ~np.isnan(minClip + maxClip):
        vmin = minClip
        vmax = maxClip
    
    graphicsShaded(data_array.E, data_array.N, data_array[first_data], mytitle, colormap, cmap_norm, minClip=vmin, maxClip=vmax, 
                   cb_ticks=cb_ticks, nSigma=nSigma, hs=hs, azdeg=azdeg, ax=ax)


def xdImage(data_array, mytitle, colormap=cc.m_CET_L9, cmap_norm='nonorm', 
        minClip=np.nan, maxClip=np.nan, cb_ticks='stats', nSigma=2,
        hs=True, azdeg=45, ax=None, clipTo3Std = True):
    """
    Uses `graphicsShaded()` to display the gridded data in data_array. All
    parameters after the name of the whizzFile are just passed through
    to `graphicsShaded()`.

    Assumes only one DataArray in the xarray dataset

    Parameters
    ----------
    data_array : 2D xarray
        The data to be imaged.
    mytitle : String
        The figure title.
    colormap : Colormap, optional
        A colour map, eg cc.m_CET_L9. The default is cc.m_CET_L9.
    cmap_norm : String, optional
        Must be one of 'nonorm' (no normalisation, ie linear stretch); 'equalize'
        (equlaization stretch); 'auto'. The default is 'nonorm'.
    minClip : Float, optional
        z -> z < minClip : minClip: z. The default is np.nan - no clipping.
    maxClip : Float, optional
        z -> z > maxClip : maxClip: z. The default is np.nan - no clipping.
    cb_ticks : TYPE, optional
        DESCRIPTION. The default is 'stats'.
    nSigma : TYPE, optional
        Not currently used. The default is 2.
    hs : Bool, optional
        hill-shading. The default is True.

    Returns
    -------
    None.

    """
    vmin = np.nan
    vmax = np.nan
    
    fd_mean = data_array.mean()
    fd_std = data_array.std()
    if clipTo3Std:
        a = fd_mean - 3.0 * fd_std
        vmin = a.data * 1
        a = fd_mean + 3.0 * fd_std
        vmax = 1 * a.data
    elif ~np.isnan(minClip + maxClip):
        vmin = minClip
        vmax = maxClip
    
    # displayShadedImage(data_array.x, data_array.y, data_array.data, mytitle)

    graphicsShaded(data_array.x, data_array.y, data_array.data, mytitle, colormap, cmap_norm, minClip=vmin, maxClip=vmax, 
                   cb_ticks=cb_ticks, nSigma=nSigma, hs=hs, azdeg=azdeg, ax=ax, origin='lower')


def graphicsShaded(e, n, z, mytitle, colormap=cc.m_CET_L9, cmap_norm='nonorm', 
                   minClip=np.nan, maxClip=np.nan, cb_ticks='stats', nSigma=2,
                   hs=True, azdeg=45, ax=None, origin='upper'):
    """
    Creates a colour image of a data array, with colour bar and grid-lines. The
    shape of z must be $shape(e) \times shape(n)$. The (e, n, z) typically are the 
    output of erm.read_ers_image().

    Parameters
    ----------
    e : np.array(Float, 1D
        The easting vector.
    n : np.array(Float, 1D)
        The northing vector.
    z : np.array(Float, 2D)
        The data to be imaged (referenced to the easting and northing positions).
    mytitle : String
        The figure title.
    colormap : Colormap, optional
        A colour map, eg cc.m_CET_L9. The default is cc.m_CET_L9.
    cmap_norm : String, optional
        Must be one of 'nonorm' (no normalisation, ie linear stretch); 'equalize'
        (equlaization stretch); 'auto'. The default is 'nonorm'.
    minClip : Float, optional
        z -> z < minClip : minClip: z. The default is np.nan - no clipping.
    maxClip : Float, optional
        z -> z > maxClip : maxClip: z. The default is np.nan - no clipping.
    cb_ticks : TYPE, optional
        DESCRIPTION. The default is 'stats'.
    nSigma : Float, optional
        Not currently used. The default is 2.
    hs : Bool, optional
        hill-shading. The default is True.
    azdeg: Float, optional
        The shading azimuth in degrees from north, defaults to 45 deg.
    ax : Axis, optional
        The Matplotlib figure axis to be plotted to. Default None, in which case a new
        figure is made.

    Returns
    -------
    None.

    """
    if not np.isnan(minClip) and not np.isnan(maxClip):
        z = np.clip(z, minClip, maxClip)
    elif np.isnan(minClip) and (not np.isnan(maxClip)):
        z = np.clip(z, np.min(z), maxClip)
    elif (not np.isnan(minClip)) and np.isnan(maxClip):
        z = np.clip(z, minClip, np.max(z))
    
    # register the supplied colormap for access via its name
    if not 'myCmap' in plt.colormaps():
        plt.register_cmap('myCmap', colormap)
    
    if ax == None:
        fig, ax = plt.subplots(figsize=(12,6))
    thou_format = tkr.FuncFormatter(util._space_thou)
    fig.suptitle(mytitle)#, fontsize=10)
    fig.subplots_adjust(top=0.85)
    
    ax.set_xlabel('Eastings [m]')#, fontsize=8)
    ax.set_ylabel('Northings [m]')#, fontsize=8)
    ax.grid(True)
    ax.axes.set_aspect('equal')
    plt.tight_layout()
    ax.xaxis.set_major_formatter(thou_format)
    ax.yaxis.set_major_formatter(thou_format)
    # for label in ax.get_xticklabels(): label.set_fontsize(6)
    # for label in ax.get_yticklabels(): label.set_fontsize(6)
    graphics.imshow_hs(z, ax, cmap='myCmap',  cmap_norm=cmap_norm, hs=hs, colorbar=True,
                   azdeg=45, altdeg = 45, blend_mode = 'alpha', alpha = 0.7,
                   extent=(e[0], e[-1], n[0], n[-1]),origin=origin)


def graphicsTernary(e, n, red, green, blue, mytitle):
    """
    Uses Matplotlib's `imshow()` to create a ternary image from three channels
    of located information. Each channel is histogram-equalised before imaging.

    Parameters
    ----------
    e : np.array(Float, 1D)
        The easting vector.
    n : np.array(Float, 1D)
        The northing vector.
    z : np.array(Float, 2D)
        The data to be imaged (referenced to the easting and northing positions).
    red : np.array(Float, 2D)
        The data for the red channel.
    green : np.array(Float, 2D)
        The data for the green channel.
    blue : np.array(Float, 2D)
        The data for the blue channel.
    mytitle : String
        The title for the image plot.

    Returns
    -------
    None.

    """
    # histogram equalise each channel
    red2 = _histEqual(red)
    green2 = _histEqual(green)
    blue2 = _histEqual(blue)
    # stack into one 3D array
    z = np.dstack((red2, green2, blue2))
    
    fig, ax = plt.subplots(figsize=(12,6))
    thou_format = tkr.FuncFormatter(util._space_thou)
    ax.imshow(e, n, z)#, cmap = 'Reds')
    ax.set_title(mytitle, fontsize=12)
    ax.xaxis.set_major_formatter(thou_format)
    ax.yaxis.set_major_formatter(thou_format)
    ax.set_xlabel('Eastings [m]', fontsize=9)
    ax.set_ylabel('Northings [m]', fontsize=9)
    ax.grid(True)
    plt.axis('equal')

    plt.show()

    
def _histEqual(img):
    """
    Performs histogram equalisation on an image.

    Parameters
    ----------
    img : 2D image array
        DESCRIPTION.

    Returns
    -------
    2D image array
        DESCRIPTION.

    """
    cleanImg = img[np.logical_not(np.isnan(img))]
    hist,bins = np.histogram(cleanImg.flatten(),256)#,[0,256])
    cdf = hist.cumsum()
    cdf_m = np.ma.masked_equal(cdf,0)
    cdf_m = (cdf_m - cdf_m.min()) / (cdf_m.max() - cdf_m.min()) * 255
    cdf = np.ma.filled(cdf_m,0).astype('uint8')
    img255 = (img - np.min(cleanImg)) / (np.max(cleanImg) - np.min(cleanImg)) * 255.0
    return cdf[img255.astype('uint8')]

    
def displayShadedImage(e, n, z, mytitle):
    """
    REDUNDANT

    Given a 2D array z located by 1D arrays e and n, plot an image of z.

    Any invalid values (NaN, Inf) of z are masked out. The plot has grid lines,
    colorbar, x and y labels (Eastings and Northings respectively) and a title.

    Parameters
    ----------
    e : 1D numpy array
        Eastings.
    n : 1D numpy array
        Northings.
    z : 2D numpy array
        Data to be imaged.
    mytitle : String
        Plot title.

    Returns
    -------
    None

    """
    from matplotlib.colors import LightSource

    my_ls = LightSource(azdeg=315, altdeg=50)
    cmap = plt.cm.nipy_spectral  # gist_earth

    zm = np.ma.masked_invalid(z)
    rgb = my_ls.shade(zm, cmap, fraction=0.2)
    # might change to image histogram-equalised zm or limit the range to 95%
    # z indices ought to be fixed in ermread
    fig, ax = plt.subplots()
    fig.dpi = 200

    ax.imshow(rgb, cmap=cmap)
    ax.set_title(mytitle, fontsize=8)
    ax.set_xlabel('Eastings [m]', fontsize=6)
    ax.set_ylabel('Northings [m]', fontsize=6)
    ax.grid(True)

    #   Much better is to run pcolormesh, steal its labels, remove it and set the
    #   labels
    #    ax.xaxis.set_ticklabels(('1', '692000', '694000', '696000', '698000',
    #                             '700000', '702000', '704000', '706000'),
    #                            fontsize=6)
    #    labels = ax.yaxis.get_ticklabels(which='major')
    #    ax.yaxis.set_ticklabels(('1', '3676000', '3674000', '3672000', '3670000',
    #                            '3668000', '3666000', '3664000', '3662000'),
    #                            fontsize=6)

    plt.axis('equal')
    plt.show()
    im = ax.imshow(zm, cmap=cmap)
    im.remove()
    fig.colorbar(im)

    return


