#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
DEPRECATED.

@author: markdransfield

Shows a figure of an image of `grid` over a `region`, using
`PyGMT`'s `grdimage()`. The `pyGMT` package is no longer used.

"""
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
from pathlib import Path
import colorcet as cc
import xarray as xr
import netCDF4 as nc4
import filebrowser as fb
# import rioxarray
import h5py
import pygmt
import matplotlib.ticker as tkr

import AirGravQC.gridFiles.graphics as graphics
import AirGravQC.utility.utility as util
import AirGravQC.gridFiles.read_ers as ers
import AirGravQC.whizzFiles.retrieveData as rd
import AirGravQC.config as config
from AirGravQC.gridFiles.graphicsShaded import graphicsShaded
from AirGravQC.gridFiles.whizz_to_xarray import whizz_to_xarray
from AirGravQC.gridFiles.xarray_to_grid import xarray_to_grid

groupName = config.groupName
projectName = config.projectName


def image_pygmt(grid, region):
    """
    Shows a figure of an image of `grid` over a `region`, using
    `PyGMT`'s `grdimage()`. The inputs can be generated by `xarray_to_grid()`.

    Parameters
    ----------
    grid : XArray
        Contains the gridded data.
    region : tuple
        Four floating point values for xmin, xmax, ymin, ymax.

    Returns
    -------
    Nothing.

    """

    plot_width = 0.12 # ie 12 cm

    # colour bar labeling
    yc_label = f'af+l{grid.attrs["long_name"]}'
    uc_label = f'y+l{grid.attrs["units"]}'

    # axis labeling and control
    xa_label = f"xag+l{grid['x'].attrs['orig_name']}"
    ya_label = f"yag+l{grid['y'].attrs['orig_name']}"
    my_title = f'+t{grid.attrs["title"]}'

    # Colour scaling
    cmin = np.nanpercentile(grid.data, 1)
    cmax = np.nanpercentile(grid.data, 99)
    print(f'z range (1st to 99th percentile) ({cmin:.4g}, {cmax:.4g})')
    if abs(cmax - cmin) < 1.0E-10:
        cmin = -1.0E-10
        cmax = 1.0E-10

    # fit the plot to a width of 12 cm
    hscale = (grid['x'].attrs['actual_range'][1] - grid['x'].attrs['actual_range'][0]) / plot_width
    myproj = f'x1:{hscale:.0f}'

    fig = pygmt.Figure()
    fig.basemap(
        frame=[xa_label, ya_label, my_title],
        region=region,
        projection=myproj,
    )
    pygmt.makecpt(cmap="viridis", series=(cmin, cmax))
    fig.grdimage(grid=grid, nan_transparent=True, cmap=True)
    fig.colorbar(position="JMR", frame=[yc_label, uc_label])
    fig.show()


