from setuptools import setup

setup(
    name='pegasusQC',
    version='0.1',
    description='Quality control for airborne gravity.',
    author='Mark Dransfield',
    author_email='dransfield.m@bigpond.com',
    packages=['pegasusQC'],
    install_requires=[
        'numpy',
        'matplotlib',
        'gdal>3.8',
        'colorcet',
        'filebrowser',
        'h5py',
        'ipympl',
        'netCDF4',
        'numba',
        'pathlib',
        'pooch',
        'pyarrow',
        'pyproj',
        'rioxarray',
        'scikit-image',
        'scipy',
        'verde',
        'xarray',
        'xrft',
    ],
)